AWSTemplateFormatVersion: "2010-09-09"
Resources:
  OpenSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: wide open
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
  PublicBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: inspector-poc-open-bucket
